-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 02:13:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_MATERIAL_CONSTRUCAO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_MATERIAL_CONSTRUCAO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS DB_MATERIAL_CONSTRUCAO DEFAULT CHARACTER SET utf8 ;
USE DB_MATERIAL_CONSTRUCAO ;

-- -----------------------------------------------------
-- Table DB_MATERIAL_CONSTRUCAO.TB_CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DB_MATERIAL_CONSTRUCAO.TB_CLIENTE (
  ID_CLIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único do cliente no sistema.',
  NO_CLIENTE VARCHAR(155) NOT NULL COMMENT 'Nome do cliente.',
  NR_RG INT NOT NULL COMMENT 'Numero do RG do cliente.',
  NR_CPF CHAR(11) NOT NULL COMMENT 'Número do Cadastro de Pessoa Física do cliente.',
  TP_CLIENTE ENUM("NOVO", "ANTIGO") NOT NULL COMMENT 'Tipo do cliente (Novo ou Antigo)',
  PRIMARY KEY (ID_CLIENTE),
  UNIQUE INDEX NR_CPF_UNIQUE (NR_CPF ASC) VISIBLE,
  UNIQUE INDEX NR_RG_UNIQUE (NR_RG ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table DB_MATERIAL_CONSTRUCAO.TB_ENDERECO_CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DB_MATERIAL_CONSTRUCAO.TB_ENDERECO_CLIENTE (
  ID_ENDERECO_CLIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único do endereco do cliente.',
  ID_CLIENTE INT NOT NULL COMMENT 'Chave sequencial única que identifica o cliente.',
  SG_UF CHAR(2) NOT NULL COMMENT 'Sigla da Unidade Federativa.',
  NO_ENDERECO VARCHAR(150) NOT NULL COMMENT 'Nome do endereço do cliente.',
  NO_CIDADE VARCHAR(100) NOT NULL COMMENT 'Nome da cidade do cliente.',
  PRIMARY KEY (ID_ENDERECO_CLIENTE),
  INDEX fk_TB_ENDERECO_USUARIO_TB_CLIENTE_idx (ID_CLIENTE ASC) VISIBLE,
  UNIQUE INDEX NO_ENDERECO_UNIQUE (NO_ENDERECO ASC) VISIBLE,
  CONSTRAINT fk_TB_ENDERECO_USUARIO_TB_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES DB_MATERIAL_CONSTRUCAO.TB_CLIENTE (ID_CLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table DB_MATERIAL_CONSTRUCAO.TB_LOJA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DB_MATERIAL_CONSTRUCAO.TB_LOJA (
  ID_LOJA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único da loja.',
  NO_LOJA VARCHAR(100) NOT NULL COMMENT 'Nome da loja.',
  NR_CNPJ VARCHAR(25) NOT NULL COMMENT 'Número do CNPJ  da loja.',
  NR_TELEFONE_LOJA VARCHAR(25) NOT NULL COMMENT 'Número do telefone da loja.',
  NO_ENDERECO_LOJA VARCHAR(150) NOT NULL COMMENT 'Nome do endereço da loja.',
  PRIMARY KEY (ID_LOJA))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table DB_MATERIAL_CONSTRUCAO.TB_PRODUTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DB_MATERIAL_CONSTRUCAO.TB_PRODUTO (
  CD_PRODUTO INT NOT NULL AUTO_INCREMENT COMMENT 'Código único sequencial do produto.',
  ID_LOJA INT NOT NULL COMMENT 'Chave sequencial única que identifica a loja.',
  NO_PRODUTO VARCHAR(200) NOT NULL COMMENT 'Nome do produto.',
  QT_PRODUTO INT NOT NULL COMMENT 'Quantidade disponivel do produto.',
  VL_PRODUTO_UNITARIO DOUBLE NOT NULL COMMENT 'Valor por unidade do produto.',
  PRIMARY KEY (CD_PRODUTO),
  INDEX fk_TB_PRODUTO_TB_LOJA1_idx (ID_LOJA ASC) VISIBLE,
  CONSTRAINT fk_TB_PRODUTO_TB_LOJA1
    FOREIGN KEY (ID_LOJA)
    REFERENCES DB_MATERIAL_CONSTRUCAO.TB_LOJA (ID_LOJA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table DB_MATERIAL_CONSTRUCAO.TB_FICHA_CONTROLE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DB_MATERIAL_CONSTRUCAO.TB_FICHA_CONTROLE (
  ID_FICHA_CONTROLE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único sequencial da ficha de controle.',
  ID_CLIENTE INT NOT NULL COMMENT 'Chave única sequencial do cliente.',
  CD_PRODUTO INT NOT NULL COMMENT 'Código único sequencial do produto. ',
  DH_PAGAMENTO DATE NULL COMMENT 'Data/Hora do pagamento da compra.',
  VL_TOTAL DOUBLE NOT NULL COMMENT 'Valor total da retirada/compra dos produtos.',
  IC_PAGO INT NOT NULL COMMENT '0 - Não pago\n1 - Pago',
  PRIMARY KEY (ID_FICHA_CONTROLE),
  INDEX fk_TB_COMPRA_TB_CLIENTE1_idx (ID_CLIENTE ASC) VISIBLE,
  INDEX fk_TB_COMPRA_TB_PRODUTO1_idx (CD_PRODUTO ASC) VISIBLE,
  CONSTRAINT fk_TB_COMPRA_TB_CLIENTE1
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES DB_MATERIAL_CONSTRUCAO.TB_CLIENTE (ID_CLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TB_COMPRA_TB_PRODUTO1
    FOREIGN KEY (CD_PRODUTO)
    REFERENCES DB_MATERIAL_CONSTRUCAO.TB_PRODUTO (CD_PRODUTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table DB_MATERIAL_CONSTRUCAO.TB_TELEFONE_CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DB_MATERIAL_CONSTRUCAO.TB_TELEFONE_CLIENTE (
  ID_TELEFONE_CLIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único do telefone do cliente.',
  ID_CLIENTE INT NOT NULL COMMENT 'Chave sequencial única do cliente.',
  NR_TELEFONE VARCHAR(20) NOT NULL COMMENT 'Numero de telefone do cliente.',
  PRIMARY KEY (ID_TELEFONE_CLIENTE),
  INDEX fk_TB_TELEFONE_CLIENTE_TB_CLIENTE1_idx (ID_CLIENTE ASC) VISIBLE,
  UNIQUE INDEX NR_TELEFONE_UNIQUE (NR_TELEFONE ASC) VISIBLE,
  CONSTRAINT fk_TB_TELEFONE_CLIENTE_TB_CLIENTE1
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES DB_MATERIAL_CONSTRUCAO.TB_CLIENTE (ID_CLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table DB_MATERIAL_CONSTRUCAO.TB_ADMINSTRADOR
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DB_MATERIAL_CONSTRUCAO.TB_ADMINSTRADOR (
  NO_LOGIN VARCHAR(100) NOT NULL,
  NO_SENHA VARCHAR(30) NOT NULL,
  PRIMARY KEY (NO_LOGIN, NO_SENHA))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;