-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 21:29:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_material_construcao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_material_construcao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_material_construcao` DEFAULT CHARACTER SET utf8mb3 ;
USE `db_material_construcao` ;

-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_ADMINISTRADOR` (
  `NO_LOGIN` VARCHAR(100) NOT NULL DEFAULT 'admin123',
  `NO_SENHA` VARCHAR(30) NOT NULL DEFAULT 'admin123',
  PRIMARY KEY (`NO_LOGIN`, `NO_SENHA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

INSERT INTO TB_ADMINISTRADOR (NO_LOGIN, NO_SENHA) VALUES ('admin123', 'admin123');

-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único do cliente no sistema.',
  `NO_CLIENTE` VARCHAR(155) NOT NULL COMMENT 'Nome do cliente.',
  `NR_RG` INT NOT NULL COMMENT 'Numero do RG do cliente.',
  `NR_CPF` CHAR(11) NOT NULL COMMENT 'Número do Cadastro de Pessoa Física do cliente.',
  `TP_CLIENTE` ENUM('NOVO', 'ANTIGO') NOT NULL COMMENT 'Tipo do cliente (Novo ou Antigo)',
  PRIMARY KEY (`ID_CLIENTE`),
  UNIQUE INDEX `NR_CPF_UNIQUE` (`NR_CPF` ASC) VISIBLE,
  UNIQUE INDEX `NR_RG_UNIQUE` (`NR_RG` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_ENDERECO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_ENDERECO_CLIENTE` (
  `ID_ENDERECO_CLIENTE` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único do endereco do cliente.',
  `ID_CLIENTE` INT NOT NULL COMMENT 'Chave sequencial única que identifica o cliente.',
  `SG_UF` CHAR(2) NOT NULL COMMENT 'Sigla da Unidade Federativa.',
  `NO_ENDERECO` VARCHAR(150) NOT NULL COMMENT 'Nome do endereço do cliente.',
  `NO_CIDADE` VARCHAR(100) NOT NULL COMMENT 'Nome da cidade do cliente.',
  PRIMARY KEY (`ID_ENDERECO_CLIENTE`),
  UNIQUE INDEX `NO_ENDERECO_UNIQUE` (`NO_ENDERECO` ASC) VISIBLE,
  INDEX `fk_TB_ENDERECO_USUARIO_TB_CLIENTE_idx` (`ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_TB_ENDERECO_USUARIO_TB_CLIENTE`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `db_material_construcao`.`TB_CLIENTE` (`ID_CLIENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_VENDA` (
  `ID_VENDA` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único sequencial da ficha de controle.',
  `ID_CLIENTE` INT NOT NULL,
  `DH_PAGAMENTO` DATE NULL DEFAULT NULL COMMENT 'Data/Hora do pagamento da compra.',
  `VL_TOTAL_VENDA` DOUBLE NOT NULL COMMENT 'Valor total da retirada/compra dos produtos.',
  `IC_PAGO` INT NOT NULL COMMENT '0 - Não pago\\n1 - Pago',
  PRIMARY KEY (`ID_VENDA`),
  INDEX `fk_tb_venda_tb_cliente1_idx` (`ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_cliente1`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `db_material_construcao`.`TB_CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_LOJA` (
  `ID_LOJA` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único da loja.',
  `NO_LOJA` VARCHAR(100) NOT NULL COMMENT 'Nome da loja.',
  `NR_CNPJ` VARCHAR(25) NOT NULL COMMENT 'Número do CNPJ  da loja.',
  PRIMARY KEY (`ID_LOJA`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;

INSERT INTO TB_LOJA (NO_LOJA, NR_CNPJ) VALUES ('Materiais de Construção Ltda.', '00.000.000/000-1');

-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_PRODUTO` (
  `CD_PRODUTO` INT NOT NULL AUTO_INCREMENT COMMENT 'Código único sequencial do produto.',
  `ID_LOJA` INT NOT NULL COMMENT 'Chave sequencial única que identifica a loja.',
  `NO_PRODUTO` VARCHAR(200) NOT NULL COMMENT 'Nome do produto.',
  `QT_PRODUTO_ESTOQUE` INT NOT NULL COMMENT 'Quantidade disponivel do produto.',
  `VL_PRODUTO_UNITARIO` DOUBLE NOT NULL COMMENT 'Valor por unidade do produto.',
  PRIMARY KEY (`CD_PRODUTO`),
  INDEX `fk_TB_PRODUTO_TB_LOJA1_idx` (`ID_LOJA` ASC) VISIBLE,
  CONSTRAINT `fk_TB_PRODUTO_TB_LOJA1`
    FOREIGN KEY (`ID_LOJA`)
    REFERENCES `db_material_construcao`.`TB_LOJA` (`ID_LOJA`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_TELEFONE_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_TELEFONE_CLIENTE` (
  `ID_TELEFONE_CLIENTE` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador sequencial único do telefone do cliente.',
  `ID_CLIENTE` INT NOT NULL COMMENT 'Chave sequencial única do cliente.',
  `NR_TELEFONE` VARCHAR(20) NOT NULL COMMENT 'Numero de telefone do cliente.',
  PRIMARY KEY (`ID_TELEFONE_CLIENTE`),
  UNIQUE INDEX `NR_TELEFONE_UNIQUE` (`NR_TELEFONE` ASC) VISIBLE,
  INDEX `fk_TB_TELEFONE_CLIENTE_TB_CLIENTE1_idx` (`ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_TB_TELEFONE_CLIENTE_TB_CLIENTE1`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `db_material_construcao`.`TB_CLIENTE` (`ID_CLIENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_PRODUTO_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_PRODUTO_VENDA` (
  `ID_PRODUTO_VENDA` INT NOT NULL AUTO_INCREMENT,
  `ID_VENDA` INT NOT NULL,
  `CD_PRODUTO` INT NOT NULL,
  `QT_PRODUTO_RETIRADO` INT NOT NULL,
  `VL_TOTAL_PRODUTO` DOUBLE NOT NULL,
  PRIMARY KEY (`ID_PRODUTO_VENDA`),
  INDEX `fk_TB_PRODUTO_VENDA_TB_PRODUTO1_idx` (`CD_PRODUTO` ASC) VISIBLE,
  INDEX `fk_TB_PRODUTO_VENDA_TB_VENDA1_idx` (`ID_VENDA` ASC) VISIBLE,
  CONSTRAINT `fk_TB_PRODUTO_VENDA_TB_PRODUTO1`
    FOREIGN KEY (`CD_PRODUTO`)
    REFERENCES `db_material_construcao`.`TB_PRODUTO` (`CD_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_PRODUTO_VENDA_TB_VENDA1`
    FOREIGN KEY (`ID_VENDA`)
    REFERENCES `db_material_construcao`.`TB_VENDA` (`ID_VENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_ENDERECO_LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_ENDERECO_LOJA` (
  `ID_ENDERECO_LOJA` INT NOT NULL AUTO_INCREMENT,
  `ID_LOJA` INT NOT NULL,
  `SG_UF` CHAR(2) NOT NULL,
  `NO_ENDERECO` VARCHAR(150) NOT NULL,
  `NO_CIDADE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_ENDERECO_LOJA`),
  INDEX `fk_TB_ENDERECO_LOJA_TB_LOJA1_idx` (`ID_LOJA` ASC) VISIBLE,
  CONSTRAINT `fk_TB_ENDERECO_LOJA_TB_LOJA1`
    FOREIGN KEY (`ID_LOJA`)
    REFERENCES `db_material_construcao`.`TB_LOJA` (`ID_LOJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO TB_ENDERECO_LOJA (ID_LOJA, SG_UF, NO_ENDERECO, NO_CIDADE)
SELECT ID_LOJA, 'DF', 'Setor Comercial Sul', 'Brasília'
FROM TB_LOJA
WHERE NO_LOJA = 'Materiais de Construção Ltda.';

-- -----------------------------------------------------
-- Table `db_material_construcao`.`TB_TELEFONE_LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_material_construcao`.`TB_TELEFONE_LOJA` (
  `ID_TELEFONE_LOJA` INT NOT NULL AUTO_INCREMENT,
  `ID_LOJA` INT NOT NULL,
  `NR_TELEFONE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_TELEFONE_LOJA`),
  INDEX `fk_TB_TELEFONE_LOJA_TB_LOJA1_idx` (`ID_LOJA` ASC) VISIBLE,
  CONSTRAINT `fk_TB_TELEFONE_LOJA_TB_LOJA1`
    FOREIGN KEY (`ID_LOJA`)
    REFERENCES `db_material_construcao`.`TB_LOJA` (`ID_LOJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO TB_TELEFONE_LOJA (ID_LOJA, NR_TELEFONE)
SELECT ID_LOJA, '(61) 99999-9999'
FROM TB_LOJA
WHERE NO_LOJA = 'Materiais de Construção Ltda.';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;